# Generated by Django 4.0.4 on 2022-05-28 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hudba', '0002_remove_band_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='band',
            name='slug',
            field=models.SlugField(null=True, verbose_name='Slug'),
        ),
    ]
