# Generated by Django 4.0.4 on 2022-05-30 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hudba', '0004_alter_band_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='genre',
            name='article',
            field=models.TextField(default='article'),
        ),
    ]
