# Generated by Django 4.0.4 on 2022-05-30 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hudba', '0005_genre_article'),
    ]

    operations = [
        migrations.AddField(
            model_name='band',
            name='article',
            field=models.TextField(default='article', help_text='Leave blank. Content will be added automatically'),
        ),
        migrations.AlterField(
            model_name='genre',
            name='article',
            field=models.TextField(default='article', help_text='Leave blank. Content will be added automatically'),
        ),
    ]
